version: '{build}'
image: Visual Studio 2017

clone_depth: 1

platform: Any CPU
configuration: Release

before_build:
  - if defined APPVEYOR_REPO_TAG_NAME set VERSION_TAG=%APPVEYOR_REPO_TAG_NAME:~1%
  - if not defined APPVEYOR_REPO_TAG_NAME set VERSION_TAG=%APPVEYOR_REPO_BRANCH%
  - bash update-assembly-info.sh

build:
  project: Fuse-Win32.sln
  verbosity: normal

test:
  assemblies:
    only:
      - Source\CodeCompletion\Outracks.CodeCompletion.CodeNinja.Tests\bin\$(configuration)\Outracks.CodeCompletion.CodeNinja.Tests.dll
      - Source\CodeCompletion\Outracks.CodeCompletion.UXNinja.Tests\bin\$(configuration)\Outracks.CodeCompletion.UXNinja.Tests.dll
      - Source\Common\Tests\bin\$(configuration)\Outracks.Common.Tests.dll
      - Source\Fuse\Tests\bin\$(configuration)\Outracks.Fuse.Protocol.Tests.dll
      - Source\Fusion\IntegrationTests\bin\$(configuration)\Fusion-IntegrationTests.exe
      - Source\Fusion\Tests\bin\$(configuration)\Outracks.Fusion.Tests.dll
      - Source\Preview\Tests\bin\$(configuration)\Fuse.Preview.Tests.dll
      - Source\Simulator\Tests\bin\$(configuration)\Outracks.Simulator.Tests.dll
      - Source\UnoHost\Tests\bin\$(configuration)\Outracks.UnoHost.Common.Tests.dll

after_build:
  - bash build-windows-installer.sh 

artifacts:
  - path: Installer\Windows\BuildOutput\Release\FuseSetup.exe
    name: Fuse-$(VERSION_TAG)-Win32

deploy:
  - provider: GitHub
    auth_token:
      secure: XSoc3Kto6ZdFfpL4d0Kxmiins6AttcF2oysozoZwmkz9SAGtpnCeCjxpKwxpsua/ # TODO: This is Lorents' personal token
    on:
      appveyor_repo_tag: true 