//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outracks.Fuse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Outracks.Fuse.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority: .
        /// </summary>
        public static string About_Authority {
            get {
                return ResourceManager.GetString("About_Authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company: .
        /// </summary>
        public static string About_Company {
            get {
                return ResourceManager.GetString("About_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires: .
        /// </summary>
        public static string About_Expires {
            get {
                return ResourceManager.GetString("About_Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued: .
        /// </summary>
        public static string About_Issued {
            get {
                return ResourceManager.GetString("About_Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License: .
        /// </summary>
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Menu {
            get {
                return ResourceManager.GetString("About_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information visit our .
        /// </summary>
        public static string About_MoreInfo1 {
            get {
                return ResourceManager.GetString("About_MoreInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to website.
        /// </summary>
        public static string About_MoreInfo2 {
            get {
                return ResourceManager.GetString("About_MoreInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not registered.
        /// </summary>
        public static string About_NotRegistered {
            get {
                return ResourceManager.GetString("About_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered to.
        /// </summary>
        public static string About_RegisteredTo {
            get {
                return ResourceManager.GetString("About_RegisteredTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About fuse X.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate fuse X.
        /// </summary>
        public static string Activate_Button {
            get {
                return ResourceManager.GetString("Activate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your activation code..
        /// </summary>
        public static string Activate_FeedbackEmpty {
            get {
                return ResourceManager.GetString("Activate_FeedbackEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activation code is not valid..
        /// </summary>
        public static string Activate_FeedbackInvalid {
            get {
                return ResourceManager.GetString("Activate_FeedbackInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter activation code.
        /// </summary>
        public static string Activate_Title {
            get {
                return ResourceManager.GetString("Activate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Auth_Text_LicensedTo1 {
            get {
                return ResourceManager.GetString("Auth_Text_LicensedTo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Auth_Text_LicensedTo2 {
            get {
                return ResourceManager.GetString("Auth_Text_LicensedTo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license has expired. Please .
        /// </summary>
        public static string Auth_Text_LicenseExpired1 {
            get {
                return ResourceManager.GetString("Auth_Text_LicenseExpired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string Auth_Text_LicenseExpired2 {
            get {
                return ResourceManager.GetString("Auth_Text_LicenseExpired2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to reactivate..
        /// </summary>
        public static string Auth_Text_LicenseExpired3 {
            get {
                return ResourceManager.GetString("Auth_Text_LicenseExpired3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please .
        /// </summary>
        public static string Auth_Text_SignIn1 {
            get {
                return ResourceManager.GetString("Auth_Text_SignIn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string Auth_Text_SignIn2 {
            get {
                return ResourceManager.GetString("Auth_Text_SignIn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to activate fuse X.
        /// </summary>
        public static string Auth_Text_SignIn3 {
            get {
                return ResourceManager.GetString("Auth_Text_SignIn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trial day left.
        /// </summary>
        public static string Auth_Text_TrialDayLeft {
            get {
                return ResourceManager.GetString("Auth_Text_TrialDayLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trial days left.
        /// </summary>
        public static string Auth_Text_TrialDaysLeft {
            get {
                return ResourceManager.GetString("Auth_Text_TrialDaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Button_Done {
            get {
                return ResourceManager.GetString("Button_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string CodeView_Devices {
            get {
                return ResourceManager.GetString("CodeView_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect this project to a device with the fuse X Preview app installed on it..
        /// </summary>
        public static string CodeView_ToolTip {
            get {
                return ResourceManager.GetString("CodeView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Dashboard_Button_Browse {
            get {
                return ResourceManager.GetString("Dashboard_Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Dashboard_Button_Create {
            get {
                return ResourceManager.GetString("Dashboard_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Dashboard_Button_Open {
            get {
                return ResourceManager.GetString("Dashboard_Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string Dashboard_Community {
            get {
                return ResourceManager.GetString("Dashboard_Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made something cool? Join a thriving
        ///community of Fuse enthusiasts.
        /// </summary>
        public static string Dashboard_Community_Text {
            get {
                return ResourceManager.GetString("Dashboard_Community_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Dashboard_Description {
            get {
                return ResourceManager.GetString("Dashboard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs.
        /// </summary>
        public static string Dashboard_Docs {
            get {
                return ResourceManager.GetString("Dashboard_Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need some technical information?
        ///Search the reference docs..
        /// </summary>
        public static string Dashboard_Docs_Text {
            get {
                return ResourceManager.GetString("Dashboard_Docs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last opened.
        /// </summary>
        public static string Dashboard_LastOpened {
            get {
                return ResourceManager.GetString("Dashboard_LastOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        public static string Dashboard_Learn {
            get {
                return ResourceManager.GetString("Dashboard_Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to Fuse? Explore our Handbook,
        ///Tutorials and Examples..
        /// </summary>
        public static string Dashboard_Learn_Text {
            get {
                return ResourceManager.GetString("Dashboard_Learn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Dashboard_Location {
            get {
                return ResourceManager.GetString("Dashboard_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Dashboard_New_Prefix {
            get {
                return ResourceManager.GetString("Dashboard_New_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Dashboard_Open_Prefix {
            get {
                return ResourceManager.GetString("Dashboard_Open_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from list.
        /// </summary>
        public static string Dashboard_Project_Remove {
            get {
                return ResourceManager.GetString("Dashboard_Project_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        public static string Dashboard_Recent_Projects {
            get {
                return ResourceManager.GetString("Dashboard_Recent_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup guide.
        /// </summary>
        public static string Dialog_SetupGuide_Caption {
            get {
                return ResourceManager.GetString("Dialog_SetupGuide_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A text editor is required to use fuse X..
        /// </summary>
        public static string Dialog_SetupGuide_Comment1 {
            get {
                return ResourceManager.GetString("Dialog_SetupGuide_Comment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We recommend .
        /// </summary>
        public static string Dialog_SetupGuide_Comment2_1 {
            get {
                return ResourceManager.GetString("Dialog_SetupGuide_Comment2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  or .
        /// </summary>
        public static string Dialog_SetupGuide_Comment2_2 {
            get {
                return ResourceManager.GetString("Dialog_SetupGuide_Comment2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , and our accompanying plugins..
        /// </summary>
        public static string Dialog_SetupGuide_Comment2_3 {
            get {
                return ResourceManager.GetString("Dialog_SetupGuide_Comment2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will look for the software on your system and help you install or update our plugins..
        /// </summary>
        public static string Dialog_SetupGuide_Comment3 {
            get {
                return ResourceManager.GetString("Dialog_SetupGuide_Comment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We also have a plugin for .
        /// </summary>
        public static string Dialog_SetupGuide_SeeAlso1 {
            get {
                return ResourceManager.GetString("Dialog_SetupGuide_SeeAlso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string Dialog_SetupGuide_SeeAlso2 {
            get {
                return ResourceManager.GetString("Dialog_SetupGuide_SeeAlso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select something to get started.
        /// </summary>
        public static string Inspector_SelectSomething {
            get {
                return ResourceManager.GetString("Inspector_SelectSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac only.
        /// </summary>
        public static string Label_MacOnly {
            get {
                return ResourceManager.GetString("Label_MacOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your language preference was updated.
        ///
        ///The new language will come into full effect next time you start fuse X..
        /// </summary>
        public static string LanguageUpdated_Text {
            get {
                return ResourceManager.GetString("LanguageUpdated_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while checking your license.
        ///
        ///This might be a temporary loss of service caused by problems in the network.
        ///
        ///Please try again later..
        /// </summary>
        public static string License_Error_Text {
            get {
                return ResourceManager.GetString("License_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Output.
        /// </summary>
        public static string LogView_AllOutput {
            get {
                return ResourceManager.GetString("LogView_AllOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string LogView_Tab_Clear {
            get {
                return ResourceManager.GetString("LogView_Tab_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogView_Tab_Log {
            get {
                return ResourceManager.GetString("LogView_Tab_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        public static string LogView_Tab_Problems {
            get {
                return ResourceManager.GetString("LogView_Tab_Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MainMenu_Edit {
            get {
                return ResourceManager.GetString("MainMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string MainMenu_Element {
            get {
                return ResourceManager.GetString("MainMenu_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MainMenu_Export {
            get {
                return ResourceManager.GetString("MainMenu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainMenu_File {
            get {
                return ResourceManager.GetString("MainMenu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MainMenu_Help {
            get {
                return ResourceManager.GetString("MainMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string MainMenu_Preview {
            get {
                return ResourceManager.GetString("MainMenu_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string MainMenu_Project {
            get {
                return ResourceManager.GetString("MainMenu_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string MainMenu_Tools {
            get {
                return ResourceManager.GetString("MainMenu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewport.
        /// </summary>
        public static string MainMenu_Viewport {
            get {
                return ResourceManager.GetString("MainMenu_Viewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string MainMenu_Window {
            get {
                return ResourceManager.GetString("MainMenu_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code.
        /// </summary>
        public static string NagScreen_Button_EnterCode {
            get {
                return ResourceManager.GetString("NagScreen_Button_EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string NagScreen_Button_SignIn {
            get {
                return ResourceManager.GetString("NagScreen_Button_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an unregistered copy.
        /// </summary>
        public static string NagScreen_Caption {
            get {
                return ResourceManager.GetString("NagScreen_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to activate now?.
        /// </summary>
        public static string NagScreen_Question {
            get {
                return ResourceManager.GetString("NagScreen_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! Thanks for trying out fuse X.
        ///
        ///Activation is required to use this software.
        ///
        ///Free Trial available:
        ///• Try all fuse X has to offer for one month.
        ///• No credit card required..
        /// </summary>
        public static string NagScreen_Text {
            get {
                return ResourceManager.GetString("NagScreen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string SubMenu_Edit_Copy {
            get {
                return ResourceManager.GetString("SubMenu_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string SubMenu_Edit_Cut {
            get {
                return ResourceManager.GetString("SubMenu_Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SubMenu_Edit_Delete {
            get {
                return ResourceManager.GetString("SubMenu_Edit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string SubMenu_Edit_Paste {
            get {
                return ResourceManager.GetString("SubMenu_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SubMenu_Edit_SelectAll {
            get {
                return ResourceManager.GetString("SubMenu_Edit_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect.
        /// </summary>
        public static string SubMenu_Element_Deselect {
            get {
                return ResourceManager.GetString("SubMenu_Element_Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate in editor.
        /// </summary>
        public static string SubMenu_Element_LocateInEditor {
            get {
                return ResourceManager.GetString("SubMenu_Element_LocateInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove element.
        /// </summary>
        public static string SubMenu_Element_Remove {
            get {
                return ResourceManager.GetString("SubMenu_Element_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean build files.
        /// </summary>
        public static string SubMenu_Export_Clean {
            get {
                return ResourceManager.GetString("SubMenu_Export_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export for Android.
        /// </summary>
        public static string SubMenu_Export_ExportForAndroid {
            get {
                return ResourceManager.GetString("SubMenu_Export_ExportForAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export for Android Emulator.
        /// </summary>
        public static string SubMenu_Export_ExportForAndroidEmulator {
            get {
                return ResourceManager.GetString("SubMenu_Export_ExportForAndroidEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export for Desktop (.NET).
        /// </summary>
        public static string SubMenu_Export_ExportForDotNet {
            get {
                return ResourceManager.GetString("SubMenu_Export_ExportForDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export for iOS.
        /// </summary>
        public static string SubMenu_Export_ExportForiOS {
            get {
                return ResourceManager.GetString("SubMenu_Export_ExportForiOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export for iOS Simulator.
        /// </summary>
        public static string SubMenu_Export_ExportForiOSSimulator {
            get {
                return ResourceManager.GetString("SubMenu_Export_ExportForiOSSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export for Desktop (native).
        /// </summary>
        public static string SubMenu_Export_ExportForNative {
            get {
                return ResourceManager.GetString("SubMenu_Export_ExportForNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string SubMenu_File_Exit {
            get {
                return ResourceManager.GetString("SubMenu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        public static string SubMenu_File_New {
            get {
                return ResourceManager.GetString("SubMenu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string SubMenu_File_Open {
            get {
                return ResourceManager.GetString("SubMenu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string SubMenu_File_Quit {
            get {
                return ResourceManager.GetString("SubMenu_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string SubMenu_Help_Community {
            get {
                return ResourceManager.GetString("SubMenu_Help_Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string SubMenu_Help_Documentation {
            get {
                return ResourceManager.GetString("SubMenu_Help_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string SubMenu_Help_Examples {
            get {
                return ResourceManager.GetString("SubMenu_Help_Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        public static string SubMenu_Help_Forums {
            get {
                return ResourceManager.GetString("SubMenu_Help_Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report issue.
        /// </summary>
        public static string SubMenu_Help_ReportIssue {
            get {
                return ResourceManager.GetString("SubMenu_Help_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string SubMenu_Help_Tutorial {
            get {
                return ResourceManager.GetString("SubMenu_Help_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview on Android.
        /// </summary>
        public static string SubMenu_Preview_Android {
            get {
                return ResourceManager.GetString("SubMenu_Preview_Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview on Android Emulator.
        /// </summary>
        public static string SubMenu_Preview_AndroidEmulator {
            get {
                return ResourceManager.GetString("SubMenu_Preview_AndroidEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build flags.
        /// </summary>
        public static string SubMenu_Preview_BuildFlags {
            get {
                return ResourceManager.GetString("SubMenu_Preview_BuildFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview on iOS.
        /// </summary>
        public static string SubMenu_Preview_iOS {
            get {
                return ResourceManager.GetString("SubMenu_Preview_iOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview on iOS Simulator.
        /// </summary>
        public static string SubMenu_Preview_iOSSimulator {
            get {
                return ResourceManager.GetString("SubMenu_Preview_iOSSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview on Desktop (native).
        /// </summary>
        public static string SubMenu_Preview_Native {
            get {
                return ResourceManager.GetString("SubMenu_Preview_Native", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        public static string SubMenu_Preview_Rebuild {
            get {
                return ResourceManager.GetString("SubMenu_Preview_Rebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect USB (Android).
        /// </summary>
        public static string SubMenu_Preview_Reconnect {
            get {
                return ResourceManager.GetString("SubMenu_Preview_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string SubMenu_Preview_Refresh {
            get {
                return ResourceManager.GetString("SubMenu_Preview_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project Folder.
        /// </summary>
        public static string SubMenu_Project_OpenFolder {
            get {
                return ResourceManager.GetString("SubMenu_Project_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Sublime Text 3.
        /// </summary>
        public static string SubMenu_Project_OpenSublime {
            get {
                return ResourceManager.GetString("SubMenu_Project_OpenSublime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Terminal.
        /// </summary>
        public static string SubMenu_Project_OpenTerminal {
            get {
                return ResourceManager.GetString("SubMenu_Project_OpenTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Visual Studio Code.
        /// </summary>
        public static string SubMenu_Project_OpenVSCode {
            get {
                return ResourceManager.GetString("SubMenu_Project_OpenVSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch Import.
        /// </summary>
        public static string SubMenu_Project_SketchImport {
            get {
                return ResourceManager.GetString("SubMenu_Project_SketchImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Uno config.
        /// </summary>
        public static string SubMenu_Tools_Config {
            get {
                return ResourceManager.GetString("SubMenu_Tools_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Atom plugin.
        /// </summary>
        public static string SubMenu_Tools_InstallAtomPlugin {
            get {
                return ResourceManager.GetString("SubMenu_Tools_InstallAtomPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Android SDK.
        /// </summary>
        public static string SubMenu_Tools_InstallSDK {
            get {
                return ResourceManager.GetString("SubMenu_Tools_InstallSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Sublime Text 3 plugin.
        /// </summary>
        public static string SubMenu_Tools_InstallSublimePlugin {
            get {
                return ResourceManager.GetString("SubMenu_Tools_InstallSublimePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Visual Studio Code extension.
        /// </summary>
        public static string SubMenu_Tools_InstallVSCodeExtension {
            get {
                return ResourceManager.GetString("SubMenu_Tools_InstallVSCodeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup guide.
        /// </summary>
        public static string SubMenu_Tools_Setup {
            get {
                return ResourceManager.GetString("SubMenu_Tools_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check automatically.
        /// </summary>
        public static string SubMenu_Updates_CheckAutomatically {
            get {
                return ResourceManager.GetString("SubMenu_Updates_CheckAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string SubMenu_Updates_CheckForUpdates {
            get {
                return ResourceManager.GetString("SubMenu_Updates_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download the latest version now?.
        /// </summary>
        public static string SubMenu_Updates_DownloadLatestQuestion {
            get {
                return ResourceManager.GetString("SubMenu_Updates_DownloadLatestQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s an update available.
        /// </summary>
        public static string SubMenu_Updates_UpdateAvailable {
            get {
                return ResourceManager.GetString("SubMenu_Updates_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Viewport.
        /// </summary>
        public static string SubMenu_Viewport_Close {
            get {
                return ResourceManager.GetString("SubMenu_Viewport_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select device.
        /// </summary>
        public static string SubMenu_Viewport_Device {
            get {
                return ResourceManager.GetString("SubMenu_Viewport_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip aspect.
        /// </summary>
        public static string SubMenu_Viewport_FlipAspect {
            get {
                return ResourceManager.GetString("SubMenu_Viewport_FlipAspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string SubMenu_Viewport_Goback {
            get {
                return ResourceManager.GetString("SubMenu_Viewport_Goback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Viewport.
        /// </summary>
        public static string SubMenu_Viewport_New {
            get {
                return ResourceManager.GetString("SubMenu_Viewport_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string SubMenu_Viewport_Restart {
            get {
                return ResourceManager.GetString("SubMenu_Viewport_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string SubMenu_Viewport_Selection {
            get {
                return ResourceManager.GetString("SubMenu_Viewport_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact mode.
        /// </summary>
        public static string SubMenu_Window_CompactMode {
            get {
                return ResourceManager.GetString("SubMenu_Window_CompactMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string SubMenu_Window_DarkTheme {
            get {
                return ResourceManager.GetString("SubMenu_Window_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep window on top.
        /// </summary>
        public static string SubMenu_Window_KeepWindowOnTop {
            get {
                return ResourceManager.GetString("SubMenu_Window_KeepWindowOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SubMenu_Window_Language {
            get {
                return ResourceManager.GetString("SubMenu_Window_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        public static string SubMenu_Window_LightTheme {
            get {
                return ResourceManager.GetString("SubMenu_Window_LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact.
        /// </summary>
        public static string Toolbar_Compact_Button {
            get {
                return ResourceManager.GetString("Toolbar_Compact_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between normal and compact mode. Click to switch mode..
        /// </summary>
        public static string Toolbar_Compact_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_Compact_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Toolbar_Selection_Button {
            get {
                return ResourceManager.GetString("Toolbar_Selection_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to select elements in the app..
        /// </summary>
        public static string Toolbar_Selection_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_Selection_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to select elements in the app. Disable to interact with the app..
        /// </summary>
        public static string Toolbar_Selection_Tooltip2 {
            get {
                return ResourceManager.GetString("Toolbar_Selection_Tooltip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch.
        /// </summary>
        public static string Toolbar_Touch_Button {
            get {
                return ResourceManager.GetString("Toolbar_Touch_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to intract with the app..
        /// </summary>
        public static string Toolbar_Touch_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_Touch_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Viewport.
        /// </summary>
        public static string Toolbar_Viewport_Button {
            get {
                return ResourceManager.GetString("Toolbar_Viewport_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add a new Viewport..
        /// </summary>
        public static string Toolbar_Viewport_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_Viewport_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a class from elements in the
        ///hierarchy and it will appear here.
        /// </summary>
        public static string Toolbox_CreateAClass_Text {
            get {
                return ResourceManager.GetString("Toolbox_CreateAClass_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag classes into the hierarchy 
        ///to insert instances of them.
        /// </summary>
        public static string Toolbox_DragClassesInto_Text {
            get {
                return ResourceManager.GetString("Toolbox_DragClassesInto_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make class from selection.
        /// </summary>
        public static string Toolbox_MakeClassFromSelection {
            get {
                return ResourceManager.GetString("Toolbox_MakeClassFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your classes.
        /// </summary>
        public static string Toolbox_SearchYourClasses {
            get {
                return ResourceManager.GetString("Toolbox_SearchYourClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your classes.
        /// </summary>
        public static string Toolbox_YourClasses {
            get {
                return ResourceManager.GetString("Toolbox_YourClasses", resourceCulture);
            }
        }
    }
}
