#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

if [ "$OSTYPE" = msys ]; then
    exec "`dirname "$SOURCE"`/uno.exe" $*
elif which mono64 > /dev/null 2>&1; then
    exec mono64 "`dirname "$SOURCE"`/uno.exe" $*
else
    exec mono "`dirname "$SOURCE"`/uno.exe" $*
fi
