#!/bin/sh

# Clean up any old install
rm -rf /usr/local/share/uno/Packages
rm -rf /usr/local/bin/fuse
rm -rf /usr/local/bin/uno
rm -rf /usr/local/bin/unotest #No longer exists, but could still be there from a previous install
rm -rf /Applications/Fuse.app #Setting BundleOverwriteAction to "upgrade" doesn't work 

# Old path
rm -rf /usr/share/uno/Packages
rm -rf /usr/bin/uno
rm -rf /usr/bin/unotest #No longer exists, but could still be there from a previous install
rm -rf /usr/bin/fuse
